name: CI

on:
  push:
    branches: [ master, develop, 'release/*' ]


env:
  IMAGE_REPO: tchelovilar/parrot-test

jobs:

  gathering_facts:

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.define_version.outputs.version }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Define Version
        id: define_version
        run: |
          if [[ "${{ github.ref }}" == *"master" ]] ; then
            VERSION=$(git tag --points-at HEAD)
            [[ "$TAG" == "" ]] && echo "Tag is required on master" && exit 1
          elif [[ "${{ github.ref }}" == *"release"* ]] ; then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(\(release/\).*\),\1,' | sed -e "s;/;-;")-${GITHUB_RUN_ID}
          else
            VERSION=dev-${GITHUB_RUN_ID}
          fi
          echo "::set-output name=version::$VERSION"

  build:
    runs-on: ubuntu-latest

    needs: gathering_facts

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build . --file Dockerfile --tag new_image

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u tchelovilar --password-stdin

      - name: Push image
        run: |
          VERSION=${{ needs.gathering_facts.outputs.version }}
          
          echo IMAGE_REPO=$IMAGE_REPO
          echo VERSION=$VERSION

          docker tag new_image $IMAGE_REPO:$VERSION
          docker push $IMAGE_REPO:$VERSION
    