name: PR_VALIDATE

on:
  push:
    branches: [ 'release/*' ]
    tags: [ .* ]
  pull_request:
    branches: [ master ]

jobs:

  validate_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate if is Tagged
        run: |
          TAG=$(git tag --points-at HEAD)
          echo TAG=$TAG
          [[ "$TAG" == "" ]] && exit 1